# start from base

FROM ubuntu:18.04
RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:jonathonf/texlive-2019 && apt-get update && apt-get -y install texlive

RUN apt-get update  && apt-get install -y gnupg
RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*
RUN tlmgr init-usertree
RUN tlmgr option repository ftp://tug.org/historic/systems/texlive/2018/tlnet-final
RUN tlmgr update --self --all # update all packages

RUN tlmgr install xcolor

RUN apt-get update && apt-get install -y software-properties-common gcc && \
    add-apt-repository -y ppa:deadsnakes/ppa

RUN apt-get update && apt-get install -y python3.6 python3-distutils python3-pip python3-apt
RUN apt-get update && apt-get -y install xvfb libfontconfig wkhtmltopdf

#RUN apt-get update && apt-get -y install texlive-latex-base
#RUN apt-get update && apt-get -y install texlive-fonts-recommended
#RUN apt-get update && apt-get -y install -y --no-install-recommends -f texlive-fonts-extra

#RUN ln -snf /usr/share/zoneinfo/Etc/UTC /etc/localtime \
#    && echo "Etc/UTC" > /etc/timezone \
#    && apt-get update \
#    && apt-get upgrade -y \
#    && apt-get install texlive-latex-base texlive-latex-extra texlive-fonts-recommended xzdec -y \
#    && rm -rf /var/lib/apt/lists/*

RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get install xzdec

# We copy just the requirements.txt first to leverage Docker cache

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app
EXPOSE 4000
RUN pip3 install -r requirements.txt

ENV FLASK_ENV=development
ENV FLASK_APP=server

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
RUN mkdir test
COPY . /app

#CMD ["flask", "run", "--host=0.0.0.0"]
#CMD [ "python3", "./server.py" ]
#CMD [ "flask", "run"]
