export const exampleText = `
I'm a data scientist with engineering skills, making me competent to analyze your data, make statistical inferences, create state-of-the-art models, and then apply these results to a web application. I believe in ?@company?@'s ?@services/products?@, and I'm especially enthusiastic about the ?@productA?@. I see how ?@productA?@ can satisfy the customer's needs with its ?@reason?@. I believe that ?@company?@ will do great things in the future, and I would like to be a part of the journey by joining your ?@group?@ to contribute ?@help?@, to make ?@company?@'s reach their vision.

My education and research experience have taught me how to start with a problem, find a solution, and make it accessible to others – work end-to-end. However, this has mainly been in a research environment. I aspire to one day have my own successful company. To achieve this conviction, I have to put my knowledge into practice in an industrial setting to fine-tune my skills. ?@company?@ will be the ultimate institution due to its ?@academyReason?@, which will develop me as a data scientist and entrepreneur.

I want to work on ?@services/products?@ that ?@reason?@. My experience as a researcher in data analysis will be helpful for ?@company?@'s ?@dataType?@ to find patterns and signals, which we can develop business strategies around. Furthermore, my experience with machine learning and deep learning on a vast set of different problems allows me to create models to make, e.g., ?@MLTask?@. Also, my engineering skills provide an excellent opportunity to make a package/application, extending the reach of the work to ?@workExtension?@. These combined experiences have a strong synergy, i.e., – I think in the big picture, I write my code so that the implementation into a product is seamless. Finally, I enjoy working on several projects at a time since I can increase my productivity substantially. This multi-project-style of working lets me jump between different projects while, e.g., compiling code or getting stuck on a problem (I usually need to work on something else for a while until the solution pops up in my head).

In my spare time, I enjoy coding on hobby projects. So my goal is to find me a coding job that I get paid for but could have done for free.
`
