export const exampleText = `
<p>I'm a data scientist with engineering skills, making me competent to analyze your data, make statistical inferences, create state-of-the-art models, and then apply these results to a web application. I believe in <strong>company</strong>'s <strong>services/products</strong>, and I'm especially enthusiastic about the <strong>productA</strong>. I see how <strong>productA</strong> can satisfy the customer's needs with its <strong>reason</strong>. I believe that <strong>company</strong> will do great things in the future, and I would like to be a part of the journey by joining your <strong>group</strong> to contribute <strong>help</strong>, to make <strong>company</strong>'s reach their vision.</p>

<p>My education and research experience have taught me how to start with a problem, find a solution, and make it accessible to others – work end-to-end. However, this has mainly been in a research environment. I aspire to one day have my own successful company. To achieve this conviction, I have to put my knowledge into practice in an industrial setting to fine-tune my skills. <strong>company</strong> will be the ultimate institution due to its <strong>academyReason</strong>, which will develop me as a data scientist and entrepreneur.</p>

<p>I want to work on <strong>services/products</strong> that <strong>reason</strong>. My experience as a researcher in data analysis will be helpful for <strong>company</strong>'s <strong>dataType</strong> to find patterns and signals, which we can develop business strategies around. Furthermore, my experience with machine learning and deep learning on a vast set of different problems allows me to create models to make, e.g., <strong>MLTask</strong>. Also, my engineering skills provide an excellent opportunity to make a package/application, extending the reach of the work to <strong>workExtension</strong>. These combined experiences have a strong synergy, i.e., – I think in the big picture, I write my code so that the implementation into a product is seamless. Finally, I enjoy working on several projects at a time since I can increase my productivity substantially. This multi-project-style of working lets me jump between different projects while, e.g., compiling code or getting stuck on a problem (I usually need to work on something else for a while until the solution pops up in my head).</p>

<p>In my spare time, I enjoy coding on hobby projects. So my goal is to find me a coding job that I get paid for but could have done for free.</p>
`
